BTP messaging : encodeBtpPacket method addition
project-chip/matter.js pull request #190
Opened 2023-06-27 18:19 UTC by mahimamandhanaa

2023-06-27 22:00 UTC, Apollon77 requested changes

2023-06-27 22:30 UTC, mahimamandhanaa commented on packages/matter.js/src/codec/BtpCodec.ts
> +            writer.writeByteArray(segmentPayload)
I cannot find this in the matter spec

2023-06-27 23:05 UTC, mahimamandhanaa commented on packages/matter.js/src/codec/BtpCodec.ts
> +        if (ackNumber !== undefined) writer.writeUInt8(ackNumber);
updated

2023-06-27 23:06 UTC, mahimamandhanaa commented on packages/matter.js/src/codec/BtpCodec.ts
> +        if (hasManagementOpcode) writer.writeUInt8(BtpOpcode.HandshakeManagementOpcode);
removed, since other than handshake msgs no payloads has managementOpcode till date

2023-06-27 23:06 UTC, mahimamandhanaa commented on packages/matter.js/src/codec/BtpCodec.ts
> +        if (messageLength !== undefined) writer.writeUInt16(messageLength);
Done

2023-06-28 09:32 UTC, Apollon77 commented on packages/matter.js/src/codec/BtpCodec.ts
> +            writer.writeByteArray(segmentPayload)
As discussed in Discord ... was bullshit from my side, ignore

2023-06-28 10:08 UTC, Apollon77 approved these changes

2023-06-28 10:09 UTC, merged