MDNS Refactoring and Multi-Node
project-chip/matter.js pull request #209
Opened 2023-07-16 16:45 UTC by Apollon77

This PR is implementing summarized the following:
* Enhance MDNS Scanner and Broadcaster to support multiple queries and announcements for diffrerent Instances/ports
* Adjust low and high level API to use the new scanners and broadcasters and allow to run multiple nodes in one node.js instance
* Adds MultiNodeDevice example file for multiple device nodes in one process
* Enhance MDNS Bradcaster to allow to specify all announcement details and remove all hardcoded things (only TCP support is still hardcoded on false)
* It also contains several fixes on MDNS level ( IPV6 zero-block decoding was wring, empty name encoding was wrong ...)
* Adds a sleep method to the time class
* Enhance controller to discover devices rather then expecting static ip/port data. Found addresses and devices are tried one afte rthe other (also passcode only pairing is so possible where all instances found are tried with one passcode until first working was found.

2023-07-17 17:05 UTC, lauckhart commented
Nice, big step forward in functionality!  Code is easily digestible too.  I added some comments, mostly small stuff except see my comment r.e. random port selection.  I'd let the kernel take care of that.

2023-07-17 17:05 UTC, lauckhart requested changes

2023-07-17 17:05 UTC, lauckhart commented on packages/matter.js/src/mdns/MdnsBroadcaster.ts
> +                        `SII=${sleepIdleInterval ?? 5000}`,  /* Sleepy Idle Interval */
Constants for these defaults (5000 & 300) may be overkill but if you destructure operationalInstanceData above you could have `{ sleepIdleInterval = 5000, sleepActiveInterval = 300 } = operationalInstanceData` which would tighten up the code and I think do a good job of documenting the defaults on the API

2023-07-17 17:12 UTC, Apollon77 commented on packages/matter.js/src/net/fake/UdpChannelFake.ts
> +        this.listeningPort = listeningPort ?? 1024 + Math.random() * 64511; // Random port 1024-65535
That's just the Fake!!Network one which is not real network at all ;-))

2023-07-17 17:15 UTC, Apollon77 commented on packages/matter.js/src/MatterController.ts
> +        if (this.controllerStorage.has("operationalServerAddress")) {
That storage entry is updated  whenever we have a "successful" connection.

2023-07-17 17:15 UTC, lauckhart commented on packages/matter.js/src/net/fake/UdpChannelFake.ts
> +        this.listeningPort = listeningPort ?? 1024 + Math.random() * 64511; // Random port 1024-65535
Hah duh

2023-07-17 17:15 UTC, lauckhart approved these changes

2023-07-18 07:42 UTC, Apollon77 commented on packages/matter.js/src/mdns/MdnsScanner.ts
> +     *
Will try to add

2023-07-18 08:14 UTC, Apollon77 commented on packages/matter-node.js/src/net/UdpChannelNode.ts
> +                remoteAddress: `${address}:${port}`,
changed some places

2023-07-18 08:17 UTC, Apollon77 commented on packages/matter.js/src/MatterController.ts
> +        if (this.controllerStorage.has("operationalServerAddress")) {
Added as own method now

2023-07-18 08:19 UTC, Apollon77 commented on packages/matter.js/src/MatterController.ts
> +            throw new PairRetransmissionLimitReachedError(`IPv${isIpv6Address ? "6" : "4"} interface not initialized for port ${operationalPort}. Can not use this address for pairing.`);
added

2023-07-18 08:21 UTC, Apollon77 commented on packages/matter.js/src/CommissioningController.ts
> +                    throw new Error("Passcode not set!");
rephrased - and no.

2023-07-18 08:40 UTC, Apollon77 commented on packages/matter.js/src/MatterServer.ts
> +            if (node instanceof CommissioningServer && !node.delayedAnnouncement) {
reafactored

2023-07-18 08:40 UTC, Apollon77 commented on packages/matter.js/src/MatterServer.ts
> +        if (node instanceof CommissioningServer) {
refactored

2023-07-18 08:40 UTC, Apollon77 commented on packages/matter.js/src/MatterServer.ts
> +        if (node instanceof CommissioningServer) {
(decided to leave it two calls for now)

2023-07-18 21:43 UTC, lauckhart approved these changes
Looks good

2023-07-18 21:43 UTC, lauckhart commented on packages/matter.js/src/CommissioningController.ts
> +                    throw new Error("To commission a new device a passcode needs to be specified i the constructor data!");
Missing "n" I think

2023-07-19 07:08 UTC, Apollon77 commented on packages/matter.js/src/CommissioningController.ts
> +                    throw new Error("To commission a new device a passcode needs to be specified i the constructor data!");
fixed

2023-07-19 07:09 UTC, Apollon77 commented
Tests fixed

2023-07-19 07:18 UTC, merged