Only run the nightly tests on the main repo not on local forks
project-chip/matter.js pull request #419
Opened 2023-10-19 16:04 UTC by sammachin

There are a couple of github actions that run on a nightly cron but if you have a fork of the repo these will likely fail.
This checks that the repo is project-chip/matter.js when then run and if not they will be skipped

2023-10-19 18:21 UTC, Apollon77 commented
Does it work with multiple if statements on one job? Or should we combine them into one?

2023-10-19 19:05 UTC, Apollon77 requested changes
Please see https://github.com/sammachin/matter.js/actions/runs/6577241130/workflow and combine the if lines. Two not supported.

2023-10-20 14:45 UTC, Apollon77 commented
Ok, I adjusted it

2023-10-20 16:53 UTC, lauckhart approved these changes

2023-10-20 21:31 UTC, merged