Updating the README.me
project-chip/matter.js pull request #434
Opened 2023-10-26 16:42 UTC by woody-apple

Updating some out of date items, some editorial items, as well as cleaning up markdown

2023-10-26 17:34 UTC, Apollon77 requested changes
Thank you, the one sentence i commented makes no sense for me and should be adjusted.

I might also do a walk over after merging here (saw some more outdated things). :-)

2023-10-26 17:34 UTC, Apollon77 commented on README.md
> +This list is a compilation of published information and own community tests. Many updates in the ecosystems happen without big announcements, so the information here can be a bit outdated and more de
@woody-apple This last sentence makes no sense

2023-10-27 17:57 UTC, woody-apple commented on README.md
> +This list is a compilation of published information and own community tests. Many updates in the ecosystems happen without big announcements, so the information here can be a bit outdated and more de
```suggestion
This list is a compilation of published information and own community tests. Many updates in the ecosystems happen without big announcements, so the information here can be a bit outdated and more device types are supported. If you find errors or added device types please open a PR or issue to report them. *Please note: The content of this table is collected from various public sources, own experiments and community feedback and might be outdated or not accurate.*
```

2023-10-27 18:32 UTC, Apollon77 approved these changes

2023-10-27 19:07 UTC, merged